#!/bin/bash
# Arch Linux init script for Tonido Plug application
# Author: Nick Davis
# Created 1-15-12

. /etc/rc.conf
. /etc/rc.d/functions

USER=tonido
TONIDODIR=/home/tonido/app/tonido
LOGFILE=/home/tonido/tonido_$USER.log

PID=$(pidof $TONIDODIR/tonidoconsole)

case "$1" in
	start)
		stat_busy "Starting Tonido Services"
		if [[ -z ${PID} ]] && su $USER -c "( cd $TONIDODIR && \
			export LD_LIBRARY_PATH=. \
			&& $TONIDODIR/tonidoconsole &>$LOGFILE &)" &> /dev/null; then 
			add_daemon tonido
			stat_done
		else
			stat_fail
			exit 1
		fi
		;;
	stop)
		stat_busy "Stopping Tonido Services"
		if [[ -n ${PID} ]] && kill $PID &>/dev/null; then
			rm_daemon tonido 
			stat_done
		else
			stat_fail
			exit 1
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
